/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsyphon_JSyphonClient */

#ifndef _Included_jsyphon_JSyphonClient
#define _Included_jsyphon_JSyphonClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsyphon_JSyphonClient
 * Method:    initWithServerDescriptionAndOptions
 * Signature: (Ljava/util/Dictionary;Ljava/util/Dictionary;)V
 */
JNIEXPORT void JNICALL Java_jsyphon_JSyphonClient_initWithServerDescriptionAndOptions
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     jsyphon_JSyphonClient
 * Method:    isValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jsyphon_JSyphonClient_isValid
  (JNIEnv *, jobject);

/*
 * Class:     jsyphon_JSyphonClient
 * Method:    serverDescription
 * Signature: ()Ljava/util/Dictionary;
 */
JNIEXPORT jobject JNICALL Java_jsyphon_JSyphonClient_serverDescription
  (JNIEnv *, jobject);

/*
 * Class:     jsyphon_JSyphonClient
 * Method:    hasNewFrame
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jsyphon_JSyphonClient_hasNewFrame
  (JNIEnv *, jobject);

/*
 * Class:     jsyphon_JSyphonClient
 * Method:    newFrameImageForContext
 * Signature: ()Ljsyphon/JSyphonImage;
 */
JNIEXPORT jobject JNICALL Java_jsyphon_JSyphonClient_newFrameImageForContext
  (JNIEnv *, jobject);

/*
 * Class:     jsyphon_JSyphonClient
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsyphon_JSyphonClient_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
