/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsyphon_JSyphonServer */

#ifndef _Included_jsyphon_JSyphonServer
#define _Included_jsyphon_JSyphonServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsyphon_JSyphonServer
 * Method:    initWithName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jsyphon_JSyphonServer_initWithName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jsyphon_JSyphonServer
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jsyphon_JSyphonServer_getName
  (JNIEnv *, jobject);

/*
 * Class:     jsyphon_JSyphonServer
 * Method:    hasClients
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jsyphon_JSyphonServer_hasClients
  (JNIEnv *, jobject);

/*
 * Class:     jsyphon_JSyphonServer
 * Method:    publishFrameTexture
 * Signature: (IIIIIIIIZ)V
 */
JNIEXPORT void JNICALL Java_jsyphon_JSyphonServer_publishFrameTexture
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     jsyphon_JSyphonServer
 * Method:    bindToDrawFrameOfSize
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jsyphon_JSyphonServer_bindToDrawFrameOfSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     jsyphon_JSyphonServer
 * Method:    unbindAndPublish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsyphon_JSyphonServer_unbindAndPublish
  (JNIEnv *, jobject);

/*
 * Class:     jsyphon_JSyphonServer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jsyphon_JSyphonServer_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
