/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsyphon_JSyphonImage */

#ifndef _Included_jsyphon_JSyphonImage
#define _Included_jsyphon_JSyphonImage
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
