/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsyphon_JSyphonServerList */

#ifndef _Included_jsyphon_JSyphonServerList
#define _Included_jsyphon_JSyphonServerList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsyphon_JSyphonServerList
 * Method:    getList
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_jsyphon_JSyphonServerList_getList
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
