/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsyphon_JSyphonImage */

#ifndef _Included_jsyphon_JSyphonImage
#define _Included_jsyphon_JSyphonImage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsyphon_JSyphonImage
 * Method:    textureName
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jsyphon_JSyphonImage_textureName
  (JNIEnv *, jobject);

/*
 * Class:     jsyphon_JSyphonImage
 * Method:    textureWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jsyphon_JSyphonImage_textureWidth
  (JNIEnv *, jobject);

/*
 * Class:     jsyphon_JSyphonImage
 * Method:    textureHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jsyphon_JSyphonImage_textureHeight
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
