/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jsyphon_JSyphonClient */

#ifndef _Included_jsyphon_JSyphonClient
#define _Included_jsyphon_JSyphonClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jsyphon_JSyphonClient
 * Method:    init
 * Signature: (Ljava/util/HashMap;)J
 */
JNIEXPORT jlong JNICALL Java_jsyphon_JSyphonClient_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jsyphon_JSyphonClient
 * Method:    setApplicationName
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jsyphon_JSyphonClient_setApplicationName
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     jsyphon_JSyphonClient
 * Method:    setServerName
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jsyphon_JSyphonClient_setServerName
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     jsyphon_JSyphonClient
 * Method:    isValid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jsyphon_JSyphonClient_isValid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jsyphon_JSyphonClient
 * Method:    serverDescription
 * Signature: (J)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_jsyphon_JSyphonClient_serverDescription
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jsyphon_JSyphonClient
 * Method:    hasNewFrame
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_jsyphon_JSyphonClient_hasNewFrame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jsyphon_JSyphonClient
 * Method:    newFrameDataForContext
 * Signature: (J)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_jsyphon_JSyphonClient_newFrameDataForContext
  (JNIEnv *, jobject, jlong);

/*
 * Class:     jsyphon_JSyphonClient
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jsyphon_JSyphonClient_stop
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
